engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
  fixme:
    enabled: true
ratings:
  paths:
    - "src/**.php"
exclude_paths:
  - ".circleci"
  - ".codeclimate.yml"
  - ".gitignore"
  - ".styleci.yml"
  - "composer.json"
  - "LICENSE"
  - "phpunit.php"
  - "phpunit.xml"
  - "readme.md"
  - "config/**/*"
  - "src/Http/Controllers/*"
  - "src/Providers/*"
  - "tests/**/*"
  - "vendor/**/*"
