engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
  fixme:
    enabled: true
ratings:
  paths:
    - "src/**.php"
exclude_paths:
  - "phpunit.php"
  - "config/**/*"
  - "src/Http/Controllers/*"
  - "src/Providers/*"
  - "tests/**/*"
  - "vendor/**/*"
