version: 2
jobs:
  build:
    docker:
      - image: ericdowell/laravel-circleci
      - image: mysql:5.7
        environment:
          - MYSQL_DATABASE=forge
          - MYSQL_USER=forge
          - MYSQL_PASSWORD=''
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_ROOT_HOST=%
    environment:
      TZ: "/usr/share/zoneinfo/America/Chicago"
    steps:
      - checkout
      - run: composer install --no-interaction --optimize-autoloader --prefer-dist
      - run: php vendor/bin/phpunit
      - store_test_results:
          path: build/junit
      - store_artifacts:
          path: build/junit
      - run: if [ -z ${CODECLIMATE_REPO_TOKEN+x} ]; then echo "CODECLIMATE_REPO_TOKEN not set"; else ./vendor/bin/test-reporter || echo 'Nothing sent, failed'; fi
